//---------------------------------------------------------------------------

#ifndef UnitMainH
#define UnitMainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <DBCtrls.hpp>
#include <Grids.hpp>
#include <Menus.hpp>
#include <XPMan.hpp>
//#include "Excel_XP_srvr.h"
#include <OleServer.hpp>
#include <Vcl.Graphics.hpp>
#include "frxClass.hpp"
#include <Vcl.Mask.hpp>
#include "UnitPacks.h"
#include "frxDBSet.hpp"
#include <Vcl.Dialogs.hpp>
#include <Vcl.Imaging.pngimage.hpp>
#include <map>
#define VersionExtended1
//---------------------------------------------------------------------------
class CheckError;
//class TSuperviosorCompare;

class TFormMain : public TForm
{
__published:	// IDE-managed Components
	TScrollBox *ScrollBox2;
	TPanel *Panel1;
	TLabel *LabelDateEnd;
	TLabel *LabelShiftLetter;
	TLabel *LabelShiftKind;
	TLabel *LabelOperators;
	TLabel *LabelSuperVisors;
	TPageControl *PageControl1;
	TTabSheet *TabSheetProducts;
	TScrollBox *ScrollBox1;
	TLabel *LabelProduct;
	TLabel *LabelIn;
	TLabel *LabelOut;
	TLabel *LabelYield;
	TLabel *LabelRemarks;
	TLabel *LabelSpeed;
	TLabel *Label1;
	TLabel *Label2;
	TLabel *Label3;
	TLabel *LabelTotal;
	TComboBox *ComboBoxProducts;
	TEdit *EditIn;
	TEdit *EditOut;
	TEdit *EditYield;
	TMemo *MemoProductRemarks;
	TButton *ButtonAddProduction;
	TStringGrid *StringGridProducts;
	TEdit *EditSpeed;
	TButton *ButtonRemoveProduction;
	TEdit *EditInTotal;
	TEdit *EditOutTotal;
	TEdit *EditYieldTotal;
	TTabSheet *TabSheetLineStatus;
	TScrollBox *ScrollBox;
	TScrollBox *ScrollBoxLineStatus;
	TLabel *LabelLineStatus;
	TLabel *Label28;
	TLabel *LabelStartLineStatus;
	TLabel *Label24;
	TLabel *Label25;
	TLabel *LabelRemarksLineStatus;
	TComboBox *ComboBoxLineStatus;
	TMemo *MemoLineStatus;
	TButton *ButtonAddLineStatus;
	TStringGrid *StringGridLineStatus;
	TButton *ButtonDeleteLineStatus;
	TDateTimePicker *DateTimePickerLineStatusStart;
	TDateTimePicker *DateTimePickerLineStatusStop;
	TEdit *EditMinuteLineStatus;
	TTabSheet *TabSheetDefects;
	TScrollBox *ScrollBoxDefects;
	TLabel *LabelDefect;
	TLabel *Label27;
	TLabel *LabelDefectsArea;
	TLabel *Label30;
	TLabel *Label31;
	TLabel *LabelDefectsSize;
	TLabel *Label26;
	TLabel *LabelDefectsNative;
	TLabel *LabelDefectDocNo;
	TComboBox *ComboBoxDefects;
	TMemo *MemoDefects;
	TButton *ButtonDefectsAdd;
	TStringGrid *StringGridDefectsBooth;
	TButton *ButtonDefectsDelete;
	TEdit *EditDefectsQuantity;
	TEdit *EditDefectsArea;
	TComboBox *ComboBoxDefectsSize;
	TStringGrid *StringGridDefectsNative;
	TButton *ButtonDefectsAddBooth;
	TButton *ButtonDefectsSave;
	TEdit *EditDefectDocNum;
	TButton *ButtonReadDocNo;
	TTabSheet *TabSheetEpuro;
	TScrollBox *ScrollBoxEpuro;
	TLabel *Label29;
	TLabel *Label33;
	TLabel *Label34;
	TLabel *Label35;
	TLabel *Label36;
	TLabel *Label55;
	TLabel *Label56;
	TLabel *Label57;
	TLabel *Label66;
	TLabel *Label32;
	TLabel *Label61;
	TLabel *Label62;
	TLabel *Label63;
	TLabel *Label64;
	TLabel *Label65;
	TLabel *Label67;
	TLabel *Label68;
	TLabel *Label69;
	TLabel *Label70;
	TLabel *Label71;
	TButton *ButtonAddEpuro;
	TButton *ButtonDeleteEpuro;
	TEdit *EditEpuroMB;
	TEdit *EditEpuroR1;
	TEdit *EditEpuroAD1;
	TEdit *EditEpuroEdi;
	TEdit *EditEpuroR2;
	TEdit *EditEpuroAD2;
	TEdit *EditEpuroMB_read;
	TEdit *EditEpuroR1_read;
	TEdit *EditEpuroAD1_read;
	TEdit *EditEpuroEdi_read;
	TEdit *EditEpuroR2_read;
	TEdit *EditEpuroAD2_read;
	TEdit *EditEpuroStartSpeed_read;
	TEdit *EditEpuroStopSpeed_read;
	TTabSheet *TabSheetCathodes;
	TScrollBox *ScrollBoxCathodes;
	TLabel *Label38;
	TLabel *LabelCath1;
	TLabel *Label42;
	TMemo *MemoCathodes;
	TButton *ButtonAddCathodes;
	TButton *Button5;
	TEdit *EditCathode1;
	TTabSheet *TabSheetMeasurement;
	TScrollBox *ScrollBoxMeasurements;
	TLabel *Label43;
	TLabel *Label45;
	TLabel *Label46;
	TLabel *Label47;
	TLabel *Label48;
	TMemo *MemoMeasurementsOpto;
	TButton *Button6;
	TStringGrid *StringGridMeasurements;
	TButton *ButtonMeasurementsDelete;
	TEdit *EditMeasurementsOptoB;
	TTabSheet *TabSheetSeparator;
	TScrollBox *ScrollBoxSeparator;
	TLabel *Label49;
	TLabel *Label51;
	TLabel *Label52;
	TLabel *Label53;
	TComboBox *ComboBoxSeparatorStart;
	TButton *ButtonAddSeparator;
	TStringGrid *StringGridSeparator;
	TButton *ButtonDeleteSeparator;
	TDateTimePicker *DateTimePickerSeparator;
	TEdit *EditSeparatorSettingsStart;
	TTabSheet *TabSheetAlarms;
	TScrollBox *ScrollBoxAlarms;
	TLabel *Label7;
	TLabel *Label8;
	TLabel *Label11;
	TLabel *Label14;
	TLabel *Label9;
	TButton *ButtonAddAlarms;
	TButton *ButtonAlarmDelete;
	TEdit *EditAlarmWorkDone;
	TEdit *EditAlarmMTComment;
	TEdit *EditAlarmComment;
	TStringGrid *StringGridAlarms;
	TDateTimePicker *DateTimePickerAlarms;
	TComboBox *ComboBoxAlarmStatus;
	TTabSheet *TabSheetLineStacker;
	TScrollBox *ScrollBoxLineStacker;
	TLabel *Label4;
	TLabel *Label5;
	TLabel *Label6;
	TLabel *Label10;
	TLabel *Label12;
	TButton *ButtonLineStackerAdd;
	TButton *ButtonRemoveLineStacker;
	TEdit *EditLineStackerContact;
	TEdit *EditLineStackerMTComment;
	TEdit *EditLineStackerProblem;
	TStringGrid *StringGridLineStacker;
	TDateTimePicker *DateTimePickerLineStacker;
	TComboBox *ComboBoxLineStackerStatus;
	TTabSheet *TabSheetCTControl;
	TScrollBox *ScrollBoxCTControl;
	TLabel *Label13;
	TLabel *Label15;
	TLabel *Label16;
	TLabel *Label17;
	TLabel *Label18;
	TButton *ButtonAddCTControl;
	TButton *ButtonDeleteCTControl;
	TEdit *EditContactCTControl;
	TEdit *EditMTCommentCTControl;
	TEdit *EditProblemCTControl;
	TStringGrid *StringGridCTControl;
	TDateTimePicker *DateTimePickerCTControl;
	TComboBox *ComboBoxCTControl;
	TTabSheet *TabSheetWasher;
	TScrollBox *ScrollBoxWasher;
	TLabel *Label19;
	TLabel *Label20;
	TLabel *Label21;
	TLabel *Label22;
	TLabel *Label23;
	TButton *ButtonAddWasher;
	TButton *ButtonDeleteWasher;
	TEdit *EditContactWasher;
	TEdit *EditMTCommentWasher;
	TEdit *EditProblemWasher;
	TStringGrid *StringGridWasher;
	TDateTimePicker *DateTimePickerWasher;
	TComboBox *ComboBoxWasher;
	TTabSheet *TabSheetGeneralRemarks;
	TScrollBox *ScrollBoxGeneralRemarks;
	TMemo *MemoGeneralRemarks;
	TMemo *MemoGeneralRemarksDatabase;
	TButton *ButtonAddGeneralRemarks;
	TButton *ButtonGeneralDelete;
	TDateTimePicker *DateTimePickerMain;
	TComboBox *ComboBoxSuperVisors;
	TButton *ButtonPrint;
	TComboBox *ComboBoxShiftLetter;
	TComboBox *ComboBoxShiftKind;
	TEdit *EditNumberOfOperators;
	TUpDown *UpDownNumberOfOperators;
	TButton *ButtonAddMain;
	TEdit *EditStartWasherSpeed;
	TEdit *EditStopWasherSpeed;
	TShape *Shape1;
	TLabel *Label72;
	TStringGrid *StringGridCathodes;
	TUpDown *UpDown1;
	TLabel *Label73;
	TEdit *EditCathode2;
	TUpDown *UpDown2;
	TLabel *Label74;
	TEdit *EditCathode3;
	TUpDown *UpDown3;
	TLabel *Label76;
	TEdit *EditCathode4;
	TUpDown *UpDown4;
	TLabel *LabelCathode5;
	TEdit *EditCathode5;
	TUpDown *UpDown5;
	TLabel *LabelCathode6;
	TEdit *EditCathode6;
	TUpDown *UpDown6;
	TLabel *LabelCathode7;
	TEdit *EditCathode7;
	TUpDown *UpDown7;
	TLabel *LabelCathode8;
	TEdit *EditCathode8;
	TUpDown *UpDown8;
	TLabel *LabelCathode9;
	TEdit *EditCathode9;
	TUpDown *UpDown9;
	TLabel *Label82;
	TEdit *EditCathode10;
	TUpDown *UpDown10;
	TLabel *LabelCathode11;
	TEdit *EditCathode11;
	TUpDown *UpDown11;
	TLabel *LabelCathode12;
	TEdit *EditCathode12;
	TUpDown *UpDown12;
	TLabel *LabelCathode13;
	TEdit *EditCathode13;
	TUpDown *UpDown13;
	TLabel *LabelCathode14A;
	TEdit *EditCathode14A;
	TUpDown *UpDown14;
	TLabel *LabelCathode14B;
	TEdit *EditCathode14B;
	TUpDown *UpDown15;
	TLabel *LabelCathode15A;
	TEdit *EditCathode15A;
	TUpDown *UpDown16;
	TLabel *LabelCathode15B;
	TEdit *EditCathode15B;
	TUpDown *UpDown17;
	TLabel *LabelCathode16;
	TEdit *EditCathode16;
	TUpDown *UpDown18;
	TLabel *Label17A;
	TEdit *EditCathode17A;
	TUpDown *UpDown19;
	TLabel *LabelCathode17B;
	TEdit *EditCathode17B;
	TUpDown *UpDown20;
	TLabel *LabelCathode18;
	TEdit *EditCathode18;
	TUpDown *UpDown21;
	TLabel *LabelCathode19;
	TEdit *EditCathode19;
	TUpDown *UpDown22;
	TLabel *LabelCathode20;
	TEdit *EditCathode20;
	TUpDown *UpDown23;
	TLabel *LabelCathode21;
	TEdit *EditCathode21;
	TUpDown *UpDown24;
	TLabel *LabelCathode22;
	TEdit *EditCathode22;
	TUpDown *UpDown25;
	TLabel *LabelCathode23;
	TEdit *EditCathode23;
	TUpDown *UpDown26;
	TLabel *LabelCathode24;
	TEdit *EditCathode24;
	TUpDown *UpDown27;
	TLabel *LabelCathode25;
	TEdit *EditCathode25;
	TUpDown *UpDown28;
	TLabel *LabelCathode26;
	TEdit *EditCathode26;
	TUpDown *UpDown29;
	TLabel *LabelCathode27;
	TEdit *EditCathode27;
	TUpDown *UpDown30;
	TLabel *LabelCathode28;
	TEdit *EditCathode28;
	TUpDown *UpDown31;
	TLabel *LabelCathode29;
	TEdit *EditCathode29;
	TUpDown *UpDown32;
	TLabel *LabelCathode30;
	TEdit *EditCathode30;
	TUpDown *UpDown33;
	TLabel *Label106;
	TEdit *EditCathode31;
	TUpDown *UpDown34;
	TLabel *LabelCathode32;
	TEdit *EditCathode32;
	TUpDown *UpDown35;
	TLabel *LabelCathode33;
	TEdit *EditCathode33;
	TUpDown *UpDown36;
	TLabel *LabelCathode34;
	TEdit *EditCathode34;
	TUpDown *UpDown37;
	TLabel *LabelCathode35;
	TEdit *EditCathode35;
	TUpDown *UpDown38;
	TLabel *LabelCathode36;
	TEdit *EditCathode36;
	TUpDown *UpDown39;
	TBevel *Bevel1;
	TEdit *EditMeasurementsOptoA;
	TEdit *EditMeasurementsOptoY;
	TEdit *EditMeasurementsHunterFY;
	TEdit *EditMeasurementsHunterFA;
	TEdit *EditMeasurementsHunterFB;
	TMemo *MemoMeasurementsHunterTop;
	TEdit *EditMeasurementsHunterGY;
	TEdit *EditMeasurementsHunterGA;
	TEdit *EditMeasurementsHunterGB;
	TMemo *MemoMeasurementsHunterBottom;
	TLabel *Label44;
	TLabel *Label77;
	TLabel *Label78;
	TLabel *Label79;
	TLabel *Label80;
	TLabel *Label81;
	TLabel *Label83;
	TLabel *LabelSavingWarrning;
	TEdit *EditSeparatorCEStart;
	TEdit *EditSeparatorVSStart;
	TDateTimePicker *DateTimePickerSeparatorChange;
	TComboBox *ComboBoxSeparatorStop;
	TEdit *EditSeparatorSettingsStop;
	TEdit *EditSeparatorVSStop;
	TEdit *EditSeparatorCEStop;
	TLabel *Label50;
	TLabel *Label54;
	TEdit *EditSeparatorPSStop;
	TEdit *EditSeparatorPSStart;
	TLabel *Label84;
	TLabel *Label85;
	TLabel *Label86;
	TLabel *Label87;
	TLabel *Label88;
	TLabel *Label89;
	TLabel *Label90;
	TLabel *Label91;
	TMainMenu *MainMenu1;
	TMenuItem *PlikFile1;
	TMenuItem *DrukujPrint1;
	TMenuItem *WyjcieExit1;
	TButton *ButtonMainRead;
	TLabel *LabelCathodesSwitchOf;
	TLabel *Label37;
	TLabel *Label39;
	TTabSheet *TabSheetReport;
	TScrollBox *ScrollBox3;
	TLabel *Label58;
	TLabel *Label59;
	TLabel *Label60;
	TButton *ButtonReport;
	TButton *ButtonPrintReport;
	TStringGrid *StringGridReport;
	TDateTimePicker *DateTimePickerReportStart;
	TComboBox *ComboBoxReportMode;
	TRichEdit *RichEditReport;
	TScrollBox *ScrollBoxReportPrint;
	TPaintBox *PaintBox1;
	TButton *ButtonPrintCurrent;
	TDateTimePicker *DateTimePickerReportStop;
	TDateTimePicker *DateTimePickerReportStartTime;
	TDateTimePicker *DateTimePickerReportStopTime;
	TComboBox *ComboBoxReportPredefMode;
	TLabel *Label75;
	TButton *ButtonExportReport;
	TComboBox *ComboBoxProdFrom;
	TComboBox *ComboBoxProdTo;
	TLabel *LabelProdFrom;
	TLabel *LabelProdTo;
	TComboBox *ComboBoxProcessOperator;
	TComboBox *ComboBoxBoothOperator;
	TLabel *Label40;
	TLabel *LabelBoothOperator;
	TCheckBox *CheckBoxLeadman;
	TCheckBox *CheckBoxDeputySupervisor;
	TCheckBox *CheckBoxDeputyProcess;
	TCheckBox *CheckBoxDeputyBooth;
	TComboBox *ComboBoxSuperVisorsGIP;
	TPanel *PanelDevelopement;
	TRadioGroup *RadioGroupMode;
	TButton *Button2;
	TEdit *Edit5;
	TMemo *MemoTest;
	TLabel *LabelLineStatusSumOfMinutes;
	TImage *ImageNextShift;
	TImage *ImagePreviousShift;
	TButton *Button1;
//	TfrxReport *frxReport1;
	TButton *ButtonFastReport;
	TLabel *LabelSecondLineStatusName;
	TMemo *MemoLineStatusDescription;
	TLabel *LabelLineStatusEnglishDescription;
	TButton *ButtonTrialTimeComparision;
	TEdit *EditIsTimeGreater;
	TDateTimePicker *DateTimePickerLeft;
	TDateTimePicker *DateTimePickerRight;
	TLabel *Label41;
	TLabel *Label92;
	TLabel *Label93;
	TLabel *Label94;
	TEdit *EditLess;
	TLabel *Label95;
	TEdit *EditEqual;
	TLabel *Label96;
	TEdit *EditEqualOrLess;
	TLabel *Label97;
	TEdit *EditEqualOrGreater;
	TLabel *Label98;
	TEdit *EditUnequal;
	TLabel *Label99;
	TUpDown *UpDownSpeed;
	TMaskEdit *MaskEdit1;
	TButton *ButtonCopyToClipboard;
	TButton *ButtonPrzepiszDoCoc;
	TComboBox *ComboBoxEndTime;
	TComboBox *ComboBoxStartTime;
	TDateTimePicker *DateTimePickerStartTime;
	TLabel *LabelDateStart;
	TShape *Shape2;
	TImage *PreviousShiftArrow;
	TImage *NextShiftArrow;
	TButton *ButtonExportToExcelDefectsGIP;
	TLabel *LabelScrap;
	TLabel *Label101;
	TEdit *EditReportedScrap;
	TEdit *EditReportedMinusDevelopmentScrap;
	TLabel *Label102;
	TLabel *Label103;
	TEdit *EditCalculatedScrap;
	TLabel *LabelDiscrepancy;
	TImage *Image1;
	TEdit *EditSeparatorSettingsStart2;
	TEdit *EditSeparatorSettingsStop2;
	TLabel *Label1VS_Start;
	TLabel *Label2PS_Start;
	TLabel *Label2PS_End;
	TLabel *Label1VS_End;
	TCheckBox *CheckBoxNewProduction;
	TButton *ButtonImportFromExcel;
	TOpenDialog *OpenDialogImportFromExcel;
	TButton *ButtonOEE;
	TButton *Report;
	TMenuItem *Option;
	TButton *ButtonParetoData;
	void __fastcall ButtonPrintClick(TObject *Sender);
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall ComboBoxSuperVisorsChange(TObject *Sender);
	void __fastcall KoniecExit1Click(TObject *Sender);
	void __fastcall ComboBoxProductsEnter(TObject *Sender);
	void __fastcall EditOutExit(TObject *Sender);
	void __fastcall ButtonAddMainClick(TObject *Sender);
	void __fastcall FormResize(TObject *Sender);
	void __fastcall ButtonAddProductionClick(TObject *Sender);
	void __fastcall PageControl1DrawTab(TCustomTabControl *Control, int TabIndex,
          const TRect &Rect, bool Active);
	void __fastcall StringGridProductsSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
	void __fastcall EditInExit(TObject *Sender);
	void __fastcall DrukujPrint1Click(TObject *Sender);
	void __fastcall ButtonRemoveProductionClick(TObject *Sender);
	void __fastcall TabSheetAlarmsEnter(TObject *Sender);
	void __fastcall ButtonAddAlarmsClick(TObject *Sender);
	void __fastcall StringGridAlarmsSelectCell(TObject *Sender, int ACol, int ARow,
          bool &CanSelect);
	void __fastcall ButtonLineStackerAddClick(TObject *Sender);
	void __fastcall StringGridLineStackerSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
	void __fastcall TabSheetLineStackerEnter(TObject *Sender);
	void __fastcall ButtonRemoveLineStackerClick(TObject *Sender);
	void __fastcall ButtonAlarmDeleteClick(TObject *Sender);
	void __fastcall StringGridCTControlSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
	void __fastcall TabSheetCTControlEnter(TObject *Sender);
	void __fastcall ButtonAddCTControlClick(TObject *Sender);
	void __fastcall ButtonDeleteCTControlClick(TObject *Sender);
	void __fastcall ButtonAddWasherClick(TObject *Sender);
	void __fastcall ButtonDeleteWasherClick(TObject *Sender);
	void __fastcall StringGridWasherSelectCell(TObject *Sender, int ACol, int ARow,
          bool &CanSelect);
	void __fastcall TabSheetWasherEnter(TObject *Sender);
	void __fastcall EditMinuteLineStatusEnter(TObject *Sender);
	void __fastcall TabSheetLineStatusEnter(TObject *Sender);
	void __fastcall PageControl1Change(TObject *Sender);
	void __fastcall ButtonAddLineStatusClick(TObject *Sender);
	void __fastcall StringGridLineStatusSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
	void __fastcall ButtonDeleteLineStatusClick(TObject *Sender);
	void __fastcall ButtonDefectsAddClick(TObject *Sender);
	void __fastcall ButtonDefectsAddBoothClick(TObject *Sender);
	void __fastcall ButtonReadDocNoClick(TObject *Sender);
	void __fastcall ButtonDefectsSaveClick(TObject *Sender);
	void __fastcall ButtonAddGeneralRemarksClick(TObject *Sender);
	void __fastcall ButtonGeneralDeleteClick(TObject *Sender);
	void __fastcall TabSheetGeneralRemarksExit(TObject *Sender);
	void __fastcall ButtonAddEpuroClick(TObject *Sender);
	void __fastcall ButtonDeleteEpuroClick(TObject *Sender);
	void __fastcall EditStartWasherSpeedExit(TObject *Sender);
	void __fastcall ButtonAddCathodesClick(TObject *Sender);
	void __fastcall EditCathode1Change(TObject *Sender);
	void __fastcall Button6Click(TObject *Sender);
	void __fastcall ButtonMeasurementsDeleteClick(TObject *Sender);
	void __fastcall DateTimePickerSeparatorChangeEnter(TObject *Sender);
	void __fastcall ButtonAddSeparatorClick(TObject *Sender);
	void __fastcall ButtonDeleteSeparatorClick(TObject *Sender);
	void __fastcall DateTimePickerSeparatorEnter(TObject *Sender);
	void __fastcall WyjcieExit1Click(TObject *Sender);
	void __fastcall ButtonMainReadClick(TObject *Sender);
	void __fastcall ButtonReportClick(TObject *Sender);
	void __fastcall ButtonPrintReportClick(TObject *Sender);
	void __fastcall PaintBox1Paint(TObject *Sender);
	void __fastcall ButtonPrintCurrentClick(TObject *Sender);
	void __fastcall EditCathode12Change(TObject *Sender);
	void __fastcall ComboBoxReportPredefModeChange(TObject *Sender);
	void __fastcall ButtonExportReportClick(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall ComboBoxLineStatusChange(TObject *Sender);
	void __fastcall ComboBoxSuperVisorsEnter(TObject *Sender);
	void __fastcall CheckBoxLeadmanClick(TObject *Sender);
	void __fastcall ComboBoxProcessOperatorEnter(TObject *Sender);
	void __fastcall CheckBoxDeputyProcessClick(TObject *Sender);
	void __fastcall ComboBoxBoothOperatorEnter(TObject *Sender);
	void __fastcall CheckBoxDeputyBoothClick(TObject *Sender);
	void __fastcall RadioGroupModeClick(TObject *Sender);
	void __fastcall ComboBoxShiftKindChange(TObject *Sender);
	void __fastcall ComboBoxShiftLetterChange(TObject *Sender);
	void __fastcall ImageNextShiftClick(TObject *Sender);
	void __fastcall ImagePreviousShiftClick(TObject *Sender);
	void __fastcall LabelDateEndClick(TObject *Sender);
	void __fastcall ButtonFastReportClick(TObject *Sender);
	void __fastcall ComboBoxLineStatusSelect(TObject *Sender);
	void __fastcall ComboBoxLineStatusDrawItem(TWinControl *Control, int Index, TRect &Rect,
          TOwnerDrawState State);
	void __fastcall ButtonTrialTimeComparisionClick(TObject *Sender);
	void __fastcall Label41Click(TObject *Sender);
	void __fastcall ComboBoxLineStatusMeasureItem(TWinControl *Control, int Index, int &Height);
	void __fastcall UpDownSpeedChangingEx(TObject *Sender, bool &AllowChange, short NewValue,
          TUpDownDirection Direction);
	void __fastcall ButtonCopyToClipboardClick(TObject *Sender);
	void __fastcall ComboBoxStartTimeChange(TObject *Sender);
	void __fastcall ComboBoxEndTimeChange(TObject *Sender);
	void __fastcall DateTimePickerStartTimeChange(TObject *Sender);
	void __fastcall DateTimePickerMainChange(TObject *Sender);
	void __fastcall ButtonPrzepiszDoCocClick(TObject *Sender);
	void __fastcall ScrollBoxLineStatusResize(TObject *Sender);
	void __fastcall ButtonExportToExcelDefectsGIPClick(TObject *Sender);
	void __fastcall Button5Click(TObject *Sender);
	void __fastcall EditSpeedExit(TObject *Sender);
	void __fastcall CheckBoxNewProductionClick(TObject *Sender);
	void __fastcall StringGridProductsDblClick(TObject *Sender);
	void __fastcall ButtonImportFromExcelClick(TObject *Sender);
	void __fastcall ButtonOEEClick(TObject *Sender);
	void __fastcall ReportClick(TObject *Sender);
	void __fastcall OptionClick(TObject *Sender);
	void __fastcall ButtonParetoDataClick(TObject *Sender);


private:	// User declarations
	void DateTimeSet();
	bool NextShift();  // Sets the next shift parameters and return true if such a shift exists in database
	bool PrevShift();  // Similar ...
	void ShiftReviewer();
public:		// User declarations
	__fastcall TFormMain(TComponent* Owner);
	void FillingUP();
	void LineStatusChangingControls(int Ind);
    bool CheckFillingOfMainEntity() throw(CheckError);
	std::map<AnsiString,int> Supervisors;
	std::map<AnsiString,int> SupervisorsGIP;
	std::map<AnsiString,int> ProcessOperators;
	std::map<AnsiString,int> BoothOperators;
	std::map<AnsiString,int> ProductNames;
	std::map<char,UnicodeString> CurrentSupervisorsGIP;
	UnicodeString IdLineStatusToLineStatus(int ID);
	//TSuperviosorCompare  SupervisorsCompare;


};
//---------------------------------------------------------------------------
extern PACKAGE TFormMain *FormMain;

	typedef TOperators (std::map<AnsiString,int>);

class CheckError
{
    public:
    enum TErrorType {ShiftLetter,ShiftType,ShiftSupervisor, Unknown } TypeOfError;
    CheckError(TErrorType);
    AnsiString Message();

};



//---------------------------------------------------------------------------
#endif
